CA_EMAIL='ahhfzwl@qq.com'
CA_EAB_KEY_ID='la-AxMi7GKMSb-u4Lk52UA'
CA_EAB_HMAC_KEY='PbjRetZRjBg-v_TvMzuQfRQD4rdDQ3aJfyQZJ1_wuJ9xqF7XKDGsccGrTG3XBGIl0-7d0bF6TXDSrEJblCVPYQ'
ACCOUNT_URL='https://acme.zerossl.com/v2/DV90/account/la-AxMi7GKMSb-u4Lk52UA'
CA_KEY_HASH='8DnXfxkrSWvthxiOVUPxIi53nX9T+kpZaDxWVeG/Dbs='
