name: Register ACME Account

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: ./acme.sh --home "$GITHUB_WORKSPACE" --register-account -m ahhfzwl@qq.com

      - run: |
          git config user.name  github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A
          git commit -m "register" || exit 0
          git push
